#!/usr/bin/env bash

set -x

_help=$(echo "$@" | grep "\-h\|--help")
if [[ $_help ]]
then
	help_message
	success
fi

base=$1
shift

branch=$2
shift

failure(){
	echo "Script exited with exit code 1"
	echo ""
	exit 1
}

success(){
	echo "Script exited with exit code 0"
	echo ""
	exit 0
}

help_message(){
	echo ""
	echo "This script takes 1 argument."
	echo "\$1 is the ref of the branch, the merge status of which we want"
	echo "Use the -h or --help flag for help"
	echo "Use the -v flag for verbose (set -x)"
	echo ""
}

if [[ -z $base || -z $branch ]]
then
	echo ""
	help_message
	failure
fi

current_head=$(git rev-parse HEAD)

fail_if_base_is_not_merged(){
	if git merge-base --is-ancestor $base $branch @
	then
	  echo "$branch is up to date with $base."
	  exit 0
	else
	  echo "You need to merge $base into $branch, or rebase $branch onto $base."
	  failure
	fi
}

fail_if_base_is_not_merged
