#!/usr/bin/env bash

verbose=$(echo "$@" | grep "\-v")
if [[ $verbose ]]
then
	set -x
fi

_help=$(echo "$@" | grep "\-h\|--help")
if [[ $_help ]]
then
	help_message
	success
fi

is_merged_ref=$1
shift

failure(){
	echo "Script exited with exit code 1"
	echo ""
	exit 1
}

success(){
	echo "Script exited with exit code 0"
	echo ""
	exit 0
}

help_message(){
	echo ""
	echo "This script takes 1 argument."
	echo "\$1 is the ref of the branch, the merge status of which we want"
	echo "Use the -h or --help flag for help"
	echo "Use the -v flag for verbose (set -x)"
	echo ""
}

if [[ -z $is_merged_ref ]]
then
	echo ""
	help_message
	failure
fi

current_head=$(git rev-parse HEAD)

fail_if_is_merged_ref_is_not_merged(){
	if git merge-base --is-ancestor remotes/origin/$is_merged_ref @
	then
	  echo "Your branch is up to date with $is_merged_ref."
	  exit 0
	else
	  echo "You need to merge / rebase onto $is_merged_ref."
	  failure
	fi
}

fail_if_is_merged_ref_is_not_merged
