#!/usr/bin/env bash

_help=$(echo "$@" | grep "\-h\|--help")
if [[ $_help ]]
then
	help_message
	success
fi

_verbose=$(echo "$@" | grep "\-h\|--help")
if [[ $_verbose ]]
then
	set -x
fi

base=$1
shift

branch=$1
shift

failure(){
	echo "Script exited with exit code 1"
	echo ""
	exit 1
}

success(){
	echo "Script exited with exit code 0"
	echo ""
	exit 0
}

help_message(){
	echo ""
	echo "This script takes 2 arguments."
	echo "We want to see if \$1 is an ancestor of \$2"
	echo "Use the -h or --help flag after the args for help"
	echo "Use the -v or --verbose flag after the args for (set -x)"
	echo ""
}

if [[ -z $base || -z $branch ]]
then
	echo ""
	help_message
	failure
fi

current_head=$(git rev-parse HEAD)

fail_if_base_is_not_merged(){
	if git merge-base --is-ancestor $base $branch
	then
	  echo "$branch is up to date with $base."
	  exit 0
	else
	  echo "You need to merge $base into $branch, or rebase $branch onto $base."
	  failure
	fi
}

fail_if_base_is_not_merged
