name: test environment variables scope
on: [pull_request]
jobs:
  test-environment-variables-scope:
    runs-on: [ubuntu-latest]
    steps:
      - name: echo environment variables
        id: echo_env
        run: |
          echo "GITHUB_SHA        $GITHUB_SHA"
          echo "GITHUB_REF        $GITHUB_REF"
          echo "GITHUB_HEAD_REF   $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF   $GITHUB_BASE_REF"
          echo "GITHUB_ACTION_REF $GITHUB_ACTION_REF"

